[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'sha256-zjM11pvnBPmfGjqMWII3OcZT6v4sL3sKB5U16vOoZyQ=' 'sha256-TDm/xn+U4uGGgOOcNH2HRPhAvx6bnQC67Fsf++4vOE4=' https://cdnjs.cloudflare.com https://www.googletagmanager.com; worker-src 'self' blob: https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' https://images.unsplash.com https://cdn.buymeacoffee.com data:; connect-src 'self' https://eexzkkypfkpscewufgrg.supabase.co https://waterservices.usgs.gov https://www.google-analytics.com; font-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self' https://eexzkkypfkpscewufgrg.supabase.co"
